In [1]:
6+8

14

In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
dataset=fetch_california_housing()
dataset

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [3]:
dataset.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [4]:
dataset.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [5]:
dataset.target_names

['MedHouseVal']

In [6]:
dataset.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [7]:
import pandas as pd
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [8]:
df['Price']=dataset.target
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  Price  
0        -122.23  4.526  
1        -122.22  3.585  
2        -122.24  3.521  
3        -122.25  3.413  
4        -122.25  3.422  
...          ...    ...  
20635    -121.09  0.781  
20636    -121.21  0.771  
20637    -121.22  0.923  
20638    -121.32  0.847  
20639    -121.24  0.894  

[20640 rows x 9 columns]

In [9]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [10]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: Price, Length: 20640, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=36)

In [12]:
x_train.shape,x_test.shape

((13828, 8), (6812, 8))

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [14]:
scaler.fit(x_train)

StandardScaler()

In [15]:
x_train=scaler.fit_transform(x_train)
x_train

array([[ 2.94615603,  1.69257444,  0.65840852, ...,  0.00631568,
        -0.67676958,  0.7291751 ],
       [-0.53712836,  0.26178584, -0.61551141, ...,  0.10882511,
        -0.78878315,  0.59982719],
       [ 0.02597188,  0.50025061, -0.14510172, ..., -0.11288116,
         0.79807576, -1.19114398],
       ...,
       [-0.46390242,  0.57973886, -0.72060079, ...,  0.24671234,
        -0.77478146,  0.69932558],
       [ 0.03045085, -0.85104973,  0.29681501, ..., -0.04515438,
         1.27880067, -1.66873629],
       [ 0.48355594, -0.69207322, -0.02275645, ..., -0.12518059,
         0.95676166, -1.25084302]])

In [16]:
x_test=scaler.transform(x_test)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
regression=LinearRegression()

In [19]:
regression.fit(x_train,y_train)

LinearRegression()

In [20]:
regression.coef_

array([ 0.83700024,  0.12271899, -0.26347102,  0.30713139, -0.0081633 ,
       -0.02764702, -0.90609856, -0.87576409])

In [21]:
regression.intercept_

2.0708259184263804

In [22]:
y_predic=regression.predict(x_test)

In [23]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [24]:
import numpy as np

In [25]:
mse=mean_squared_error(y_test,y_predic)
print(mse)
mae=mean_squared_error(y_test,y_predic)
print(mae)
print(np.sqrt(mse))

0.5335029155157139
0.5335029155157139
0.730412839095613


In [26]:
from sklearn.metrics import r2_score

In [27]:
r2_score(y_test,y_predic)

0.5875394343499214

In [28]:
from sklearn.linear_model import Ridge
ridge=Ridge()
ridge.fit(x_train,y_train)


Ridge()

In [29]:
y_predic=ridge.predict(x_test)
mse=mean_squared_error(y_test,y_predic)
print(mse)
mae=mean_squared_error(y_test,y_predic)
print(mae)
print(np.sqrt(mse))

0.5335039735183067
0.5335039735183067
0.730413563344977


In [30]:
from sklearn.linear_model import Lasso
lasso=Lasso()
lasso.fit(x_train,y_train)


Lasso()

In [31]:
y_predic=lasso.predict(x_test)
mse=mean_squared_error(y_test,y_predic)
print(mse)
mae=mean_squared_error(y_test,y_predic)
print(mae)
print(np.sqrt(mse))

1.2935112672240048
1.2935112672240048
1.1373263679454568


In [32]:
from sklearn.linear_model import ElasticNet
elastic=ElasticNet()
elastic.fit(x_train,y_train)

ElasticNet()

In [33]:
y_predic=elastic.predict(x_test)
mse=mean_squared_error(y_test,y_predic)
print(mse)
mae=mean_squared_error(y_test,y_predic)
print(mae)
print(np.sqrt(mse))

1.0289937580534225
1.0289937580534225
1.0143932955483403
